image: Ubuntu1804
stack: node 12
branches:
  only:
      - master
cache: node_modules
platform:
  - x64
build: off
install:
  - npm install -g npm@latest
test_script:
- npm run lint && npm test # скрипт сборки