image: Ubuntu1804
stack: node 12
branches:
  only:
      - master
cache: node_modules
environment:
  nodejs_version: "20.11.1"
platform:
  - x64
build: off
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
test_script:
- npm run lint && npm test # скрипт сборки